spring.application.name=freshlink
spring.profiles.default=dev

# Actuator exposure
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when_authorized

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.default-schema=freshlink
spring.flyway.schemas=freshlink
spring.flyway.create-schemas=true
spring.jpa.properties.hibernate.default_schema=freshlink
