spring.datasource.url=jdbc:postgresql://localhost:5432/freshlink
spring.datasource.username=freshlink
spring.datasource.password=freshlink

spring.docker.compose.enabled=true
spring.docker.compose.lifecycle-management=start_and_stop
spring.docker.compose.file=compose.yaml
